FROM python:3.12

WORKDIR /app

COPY . /app

COPY disk_snapshot_list /etc/snapshot/config

RUN pip install --no-cache-dir -r requirements.txt

ARG KT_CLOUD_ACCOUNT_NAME
ARG KT_CLOUD_API_KEY
ARG KT_CLOUD_SECRET_KEY
ARG TELEGRAM_BOT_TOKEN
ARG TELEGRAM_CHAT_ID
ARG TIME_START_DAY
ARG TIME_CYCLE
ARG TIME_CREATE_TIME
ARG TIME_DELETE_TIME

ENV KT_CLOUD_ACCOUNT_NAME=${KT_CLOUD_ACCOUNT_NAME}
ENV KT_CLOUD_API_KEY=${KT_CLOUD_API_KEY}
ENV KT_CLOUD_SECRET_KEY=${KT_CLOUD_SECRET_KEY}
ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
ENV TIME_START_DATE=${TIME_START_DATE}
ENV TIME_CYCLE=${TIME_CYCLE}
ENV TIME_CREATE_TIME=${TIME_CREATE_TIME}
ENV TIME_DELETE_TIME=${TIME_DELETE_TIME}

ENV PYTHONPATH=/app

CMD ["python", "src/main.py"]