name: "[Dispatch] NCR push"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'image version'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: NCR login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCR_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.NCR_URL }}/${{ secrets.DOCKER_REPO }}:${{ env.VERSION }}
